// wordlists.js — AI phrases, replacements, discourse markers, word lists

export const AI_PHRASES = [
  // High confidence (weight 1.0)
  { phrase: 'it is important to note that', weight: 1.0 },
  { phrase: 'it is worth noting that', weight: 1.0 },
  { phrase: 'in today\'s digital age', weight: 1.0 },
  { phrase: 'in today\'s fast-paced world', weight: 1.0 },
  { phrase: 'plays a crucial role', weight: 1.0 },
  { phrase: 'it\'s important to note', weight: 1.0 },
  { phrase: 'delve into', weight: 1.0 },
  { phrase: 'delves into', weight: 1.0 },
  { phrase: 'navigating the complexities', weight: 1.0 },
  { phrase: 'underscores the importance', weight: 1.0 },
  { phrase: 'in the realm of', weight: 1.0 },
  { phrase: 'it is essential to', weight: 1.0 },
  { phrase: 'serves as a testament', weight: 1.0 },
  { phrase: 'a testament to', weight: 0.9 },
  { phrase: 'at the forefront of', weight: 0.9 },
  { phrase: 'the landscape of', weight: 0.9 },
  { phrase: 'ever-evolving', weight: 0.9 },
  { phrase: 'paradigm shift', weight: 0.9 },
  { phrase: 'holistic approach', weight: 0.9 },
  { phrase: 'game-changer', weight: 0.8 },

  // Medium confidence (weight 0.5-0.7)
  { phrase: 'furthermore', weight: 0.7 },
  { phrase: 'moreover', weight: 0.7 },
  { phrase: 'additionally', weight: 0.7 },
  { phrase: 'consequently', weight: 0.6 },
  { phrase: 'in conclusion', weight: 0.7 },
  { phrase: 'to summarize', weight: 0.6 },
  { phrase: 'it can be argued that', weight: 0.7 },
  { phrase: 'on the other hand', weight: 0.5 },
  { phrase: 'in light of', weight: 0.6 },
  { phrase: 'with regard to', weight: 0.6 },
  { phrase: 'in terms of', weight: 0.5 },
  { phrase: 'as a result', weight: 0.5 },
  { phrase: 'in order to', weight: 0.5 },
  { phrase: 'plays a vital role', weight: 0.7 },
  { phrase: 'plays an important role', weight: 0.7 },
  { phrase: 'is a key factor', weight: 0.6 },
  { phrase: 'multifaceted', weight: 0.7 },
  { phrase: 'foster', weight: 0.6 },
  { phrase: 'leverage', weight: 0.6 },
  { phrase: 'utilizing', weight: 0.6 },
  { phrase: 'facilitate', weight: 0.6 },
  { phrase: 'encompasses', weight: 0.6 },
  { phrase: 'comprehensive', weight: 0.5 },
  { phrase: 'groundbreaking', weight: 0.6 },
  { phrase: 'innovative', weight: 0.5 },
  { phrase: 'cutting-edge', weight: 0.6 },
  { phrase: 'seamless', weight: 0.6 },
  { phrase: 'robust', weight: 0.5 },
  { phrase: 'pivotal', weight: 0.6 },
  { phrase: 'nuanced', weight: 0.6 },
  { phrase: 'intricate', weight: 0.5 },
  { phrase: 'noteworthy', weight: 0.6 },
  { phrase: 'indispensable', weight: 0.6 },
  { phrase: 'paramount', weight: 0.7 },
  { phrase: 'imperative', weight: 0.6 },

  // Lower confidence (weight 0.25-0.4)
  { phrase: 'therefore', weight: 0.4 },
  { phrase: 'nevertheless', weight: 0.4 },
  { phrase: 'nonetheless', weight: 0.4 },
  { phrase: 'thus', weight: 0.3 },
  { phrase: 'hence', weight: 0.35 },
  { phrase: 'whereas', weight: 0.3 },
  { phrase: 'specifically', weight: 0.3 },
  { phrase: 'significantly', weight: 0.35 },
  { phrase: 'ultimately', weight: 0.35 },
  { phrase: 'essentially', weight: 0.35 },
  { phrase: 'particularly', weight: 0.3 },
  { phrase: 'enhance', weight: 0.35 },
  { phrase: 'optimize', weight: 0.35 },
  { phrase: 'streamline', weight: 0.4 },
  { phrase: 'empower', weight: 0.4 },
  { phrase: 'transformative', weight: 0.4 },
  { phrase: 'landscape', weight: 0.35 },
  { phrase: 'crucial', weight: 0.35 },
  { phrase: 'realm', weight: 0.4 },
  { phrase: 'myriad', weight: 0.4 },
  { phrase: 'plethora', weight: 0.4 },
  { phrase: 'tapestry', weight: 0.5 },
  { phrase: 'resonate', weight: 0.4 },
  { phrase: 'underscore', weight: 0.4 },
  { phrase: 'bolster', weight: 0.4 },
  { phrase: 'juxtaposition', weight: 0.5 },
  { phrase: 'synergy', weight: 0.5 },
  { phrase: 'burgeoning', weight: 0.5 },
  { phrase: 'nascent', weight: 0.4 },
  { phrase: 'ubiquitous', weight: 0.4 }
];

// NOTE: Replacements must NOT end with punctuation (commas, colons, periods).
// The humanizer's replaceAIPhrases() handles surrounding punctuation context.
export const AI_PHRASE_REPLACEMENTS = new Map([
  ['it is important to note that', ['Worth mentioning', 'One thing to know', 'Keep in mind that']],
  ['it is worth noting that', ['Interestingly', 'You should know that', 'Something to note']],
  ['in today\'s digital age', ['These days', 'Right now', 'Currently']],
  ['in today\'s fast-paced world', ['With how fast things move', 'Given how quickly things change', 'Nowadays']],
  ['plays a crucial role', ['really matters', 'is a big deal', 'makes a real difference']],
  ['delve into', ['dig into', 'look at', 'explore']],
  ['delves into', ['digs into', 'looks at', 'explores']],
  ['navigating the complexities', ['dealing with the tricky parts', 'working through the details', 'figuring out']],
  ['underscores the importance', ['shows why it matters', 'highlights how important', 'makes clear why']],
  ['in the realm of', ['in', 'when it comes to', 'in the world of']],
  ['it is essential to', ['you need to', 'it\'s key to', 'make sure to']],
  ['furthermore', ['also', 'plus', 'on top of that']],
  ['moreover', ['also', 'what\'s more', 'and']],
  ['additionally', ['also', 'plus', 'and']],
  ['consequently', ['so', 'because of this', 'as a result']],
  ['in conclusion', ['to wrap up', 'all in all', 'bottom line']],
  ['in order to', ['to', 'so you can', 'for']],
  ['in light of', ['given', 'considering', 'because of']],
  ['with regard to', ['about', 'regarding', 'when it comes to']],
  ['in terms of', ['for', 'when it comes to', 'regarding']],
  ['multifaceted', ['complex', 'varied', 'many-sided']],
  ['utilizing', ['using', 'working with', 'relying on']],
  ['facilitate', ['help', 'make easier', 'support']],
  ['encompasses', ['includes', 'covers', 'takes in']],
  ['comprehensive', ['thorough', 'complete', 'full']],
  ['leverage', ['use', 'take advantage of', 'build on']],
  ['foster', ['encourage', 'support', 'build']],
  ['seamless', ['smooth', 'easy', 'simple']],
  ['robust', ['strong', 'solid', 'reliable']],
  ['pivotal', ['key', 'critical', 'central']],
  ['paramount', ['most important', 'top priority', 'critical']],
  ['imperative', ['essential', 'a must', 'necessary']]
]);

export const DISCOURSE_MARKERS = [
  'Well,', 'Honestly,', 'Look,', 'I mean,', 'Basically,',
  'Actually,', 'Anyway,', 'So,', 'Right,', 'Sure,',
  'Okay so,', 'Thing is,', 'Here\'s the deal:', 'Point is,',
  'Real talk,', 'Truth is,', 'Funny thing is,'
];

export const SENTENCE_STARTERS_AI = new Set([
  'this', 'it', 'the', 'in', 'additionally', 'furthermore',
  'moreover', 'however', 'consequently', 'therefore',
  'nevertheless', 'specifically', 'ultimately', 'essentially'
]);

export const FILLER_PHRASES = [
  'kind of', 'sort of', 'I think', 'probably',
  'pretty much', 'more or less', 'in a way',
  'to be honest', 'if you ask me'
];

export const FORMAL_TO_CASUAL = new Map([
  ['utilize', 'use'],
  ['commence', 'start'],
  ['approximately', 'about'],
  ['terminate', 'end'],
  ['sufficient', 'enough'],
  ['demonstrate', 'show'],
  ['implement', 'set up'],
  ['subsequent', 'next'],
  ['prior to', 'before'],
  ['regarding', 'about'],
  ['numerous', 'many'],
  ['obtain', 'get'],
  ['acquire', 'get'],
  ['assist', 'help'],
  ['endeavor', 'try'],
  ['accomplish', 'do'],
  ['possess', 'have'],
  ['inquire', 'ask'],
  ['indicate', 'show'],
  ['substantial', 'big'],
  ['frequently', 'often'],
  ['commence', 'begin'],
  ['purchase', 'buy'],
  ['reside', 'live'],
  ['construct', 'build'],
  ['eliminate', 'remove'],
  ['establish', 'set up'],
  ['fundamental', 'basic'],
  ['magnificent', 'great'],
  ['additional', 'more'],
  ['concerning', 'about']
]);

export const CONTRACTION_MAP = new Map([
  ['do not', "don't"],
  ['does not', "doesn't"],
  ['did not', "didn't"],
  ['is not', "isn't"],
  ['are not', "aren't"],
  ['was not', "wasn't"],
  ['were not', "weren't"],
  ['has not', "hasn't"],
  ['have not', "haven't"],
  ['had not', "hadn't"],
  ['will not', "won't"],
  ['would not', "wouldn't"],
  ['could not', "couldn't"],
  ['should not', "shouldn't"],
  ['can not', "can't"],
  ['cannot', "can't"],
  ['it is', "it's"],
  ['it has', "it's"],
  ['that is', "that's"],
  ['there is', "there's"],
  ['they are', "they're"],
  ['we are', "we're"],
  ['you are', "you're"],
  ['i am', "I'm"],
  ['i have', "I've"],
  ['i will', "I'll"],
  ['i would', "I'd"],
  ['he is', "he's"],
  ['she is', "she's"],
  ['who is', "who's"],
  ['what is', "what's"],
  ['let us', "let's"]
]);
